# Generated by Django 4.1.13 on 2025-02-16 20:20

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrimeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dr_no",
                    models.CharField(db_column="DR_NO", max_length=20, unique=True),
                ),
                ("date_reported", models.DateField(db_column="Date Rptd")),
                ("date_occurred", models.DateField(db_column="DATE OCC")),
                ("time_occurred", models.IntegerField(db_column="TIME OCC")),
                ("area", models.IntegerField(db_column="AREA")),
                ("area_name", models.CharField(db_column="AREA NAME", max_length=100)),
                ("crm_cd", models.IntegerField(db_column="Crm Cd")),
                (
                    "crm_cd_desc",
                    models.CharField(db_column="Crm Cd Desc", max_length=255),
                ),
                (
                    "victim_age",
                    models.IntegerField(blank=True, db_column="Vict Age", null=True),
                ),
                (
                    "victim_sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("X", "Unknown")],
                        db_column="Vict Sex",
                        max_length=1,
                    ),
                ),
                ("premises", models.CharField(db_column="Premis Desc", max_length=255)),
                ("status", models.CharField(db_column="Status", max_length=50)),
                ("location", models.CharField(db_column="LOCATION", max_length=255)),
                ("lat", models.FloatField(db_column="LAT")),
                ("lon", models.FloatField(db_column="LON")),
            ],
            options={
                "db_table": "crime_api_crimereport",
            },
        ),
        migrations.CreateModel(
            name="Upvote",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True,
                        default=bson.objectid.ObjectId,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id", models.IntegerField()),
                ("officer_name", models.CharField(max_length=100)),
                ("officer_email", models.EmailField(max_length=254)),
                ("officer_badge", models.CharField(max_length=20)),
                (
                    "crime_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crime_api.crimereport",
                    ),
                ),
            ],
            options={
                "db_table": "crime_api_upvote",
                "unique_together": {("crime_report", "officer_email")},
            },
        ),
    ]
